name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Kaniko build
      uses: aevea/action-kaniko@master
      with:
        registry: https://index.docker.io/v1
        image: bac11/rust-server
        username: ${{ secrets.DOCKERHUB_USERNAME  }}
        password: ${{ secrets.DOCKERHUB_PASSWORD  }}
        tag_with_latest: true
        tag: $(date +%s)
        path: .
        build_file: Dockerfile
        debug: true
