name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rust-server:$(date +%s) --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rust-server:latest
    - name: Push Docker image
      run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rust-server:$(date +%s)
    - name: Push Docker image
      run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rust-server:latest
      
